# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/movie-night

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests!
      - run: yarn lint
  deploy-prod:
    docker:
      - image: circleci/node:lts
    working_directory: ~/movie-night
    steps:
      - add_ssh_keys:
            fingerprints:
              - "40:ae:79:a2:2e:79:99:fd:5c:8d:72:d2:64:ba:da:a5"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build application
      - run: yarn build

      # Deploy application
      - run:
          name: Deploy if tests pass and branch is Master
          command: |
            git config --global user.email "${GIT_EMAIL}"
            git config --global user.name "${GIT_NAME}"
            git push origin --delete gh-pages
            git add -f dist
            git commit -m "Deploy katy-ereira-ltd/movie-night to github.com/katy-ereira-ltd/movie-night.git:gh-pages"
            git subtree push --prefix dist origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master